### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by trollglodita** [AurelioDeRosa/Audero-Audio-Player#1]
This version is for Phonegap 2.3. Is there any updated version of this project?

**Comment by AurelioDeRosa** [comment]
Hi. Unfortunately this is the only version as this was a demo developed for an [article on Tuts+](http://code.tutsplus.com/tutorials/build-an-audioplayer-with-phonegap-application-setup--mobile-16347). If you want to update it, feel free to fork the project.

**Comment by trollglodita** [comment]
I think I will. But could you tell me how was the navigation of the file systems of the device? Was the same behaviour that the `<input type="file" />` feature provides allowing to look in device directory?

**Comment by AurelioDeRosa** [comment]
The core method is called `Application.updateMediaList()` and you can find it in file `application.js`.

**Comment by trollglodita** [comment]
Thanks!
